name: jsonz_generator
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: Tobe O <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  code_builder: ^1.0.0
  millisecond: ^0.1.0
  jsonz:
    path: ../jsonz
  recase: ^1.0.0
  source_gen: ^0.7.0

dev_dependencies:
  build_runner: ^0.5.0
